name: 打包Nextjs项目
on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 设置node指定版本
      uses: actions/setup-node@v3
      with:
        node-version: 20.13.1

    - name: 安装依赖 & 打包项目
      run: | 
        npm install
        npm run build

    - name: 部署
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: out

    - name: 创建 .nojekyll 文件，避免 “_” 路径问题
      run: touch out/.nojekyll

    - name: 登陆DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCHER_HUB_USERNAME }}
        password: ${{ secrets.DOCHER_HUB_TOKEN }}

    - name: 构建并推送到Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: studentming/imaginifty:latest