name: 打包Nextjs项目
on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 登陆DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCHER_HUB_USERNAME }}
        password: ${{ secrets.DOCHER_HUB_TOKEN }}

    - name: 构建并推送到Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: studentming/imaginifty:latest